"""empty message

Revision ID: 0d1611f0ce11
Revises: 3317c72ece8e
Create Date: 2021-04-08 02:08:33.556938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d1611f0ce11'
down_revision = '3317c72ece8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('object_Name', sa.String(length=50), nullable=True))
    op.drop_column('favorites', 'object_Id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('object_Id', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('favorites', 'object_Name')
    # ### end Alembic commands ###
